name: Build
on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions: 
            actions: read
            contents: write
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "yarn"
            - run: yarn install --frozen-lockfile
            - run: yarn builddocsts
            - run: yarn distdocs
              env:
                  # https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md#try-bots-and-waterfall
                  CHROME_DEVEL_SANDBOX: ""
                  GATSBY_GITHUB_REPOSITORY: ${{ github.repository }}
                  GATSBY_GITHUB_REF: ${{ github.ref }}
                  GATSBY_GITHUB_SHA: ${{ github.sha }}
                  NODE_OPTIONS: --max-old-space-size=4096
            - name: github pages
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./public
                  force_orphan: true
